apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: my-nginx
        image: sickp/alpine-nginx:1.13
        ports:
        - containerPort: 80
