apiVersion: v1
kind: Service
metadata:
  name: my-frontend
  labels:
    app: my-frontend
spec:
  type: NodePort
  selector:
    app: my-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: my-frontend
spec:
  template:
    metadata:
      labels:
        app: my-frontend
    spec:
      containers:
      - name: my-nginx
        image: sickp/alpine-nginx:1.13
        ports:
        - containerPort: 80
