apiVersion: v1
kind: Pod
metadata:
  name: test-rbd-pod
spec:
  containers:
  - name: test-rbd-pod
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/rbd"
      name: rbdpd
  volumes:
  - name: rbdpd
    rbd:
      monitors:
      - 192.168.28.182:6789
      pool: kube
      image: test-pod01
      user: admin
      secretRef:
        name: ceph-secret
      fsType: ext4
      readOnly: false

