# ownCloud with MariaDB/MySQL
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: example
# Database name: pick any name
# Database host: replace "localhost" with "mysql"
version: '2'
services:
  owncloud:
    image: owncloud
    restart: always
    volumes:
      - "./ownhtml:/var/www/html"
      - "./ownData:/data"
    ports:
      - 8021:80
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.6
    restart: always
    volumes:
        - "./mysqldata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456qazwsx
      MYSQL_DATABASE: ownCloud
      MYSQL_USER: linux100
      MYSQL_PASSWORD: 123456
