apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-linux100-www
spec:
  rules:
  - host: linux100.cc
    http:
      paths:
      - path: /
        backend:
          serviceName: my-frontend
          servicePort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-linux100-xxx
spec:
  rules:
  - host: xxx.linux100.cc
    http:
      paths:
      - path: /
        backend:
          serviceName: my-frontend
          servicePort: 80
