apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-weave
  namespace: kube-system
spec:
  rules:
  - host: scope.weave.io
    http:
      paths:
      - path: /
        backend:
          serviceName: weave-scope-app
          servicePort: 80
