kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-rbd-pv-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1024Mi
  selector:
    matchLabels:
      vol: test-rbd-pv