apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-rbd-pv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-rbd-pv
    spec:
      containers:
      - name: demo-rbd-pv
        image: mritd/demo
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/data"
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: test-rbd-pv-pvc