apiVersion: v1
kind: Service
metadata:
  name: nginx-ds02
  labels:
    app: nginx-ds02
spec:
  type: NodePort
  selector:
    app: nginx-ds02
  ports:
  - name: http
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ds02
spec:
  template:
    metadata:
      labels:
        app: nginx-ds02
    spec:
      containers:
      - name: my-nginx
        image: hub.linux100.cc/k8s/nginx:1.7.9
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: linux100