apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
spec:
  rules:
  - host: jenkins.linux100.cc
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
        path: /
